apiVersion: kodekloud/examplevoting_vote:v1
"kind: Service"
kind: Service
metadata:
  name: vote-service
  namespace: examplevoting
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  externalIPs:
    -root.example.com
  loadBalancerIP:         # This field is deprecated and should not be used.
  loadBalancerSourceRanges: # This field is deprecated and should not be used.
  healthCheckNodePort:    # This field is deprecated and should not be used.
  publishNotReadyAddresses: false 
