apiVersion: kodekloud/examplevoting_vote:v1
kind: Service
metadata:
  name: vote-service
  namespace: examplevoting
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
  sessionAffinity: None
  clusterIP: None
  externalIPs: []  # This field is deprecated and should not be used.
  externalName: ""  # This field is deprecated and should not be used.
  loadBalancerIP:         # This field is deprecated and should not be used.
  loadBalancerSourceRanges: # This field is deprecated and should not be used.
  healthCheckNodePort:    # This field is deprecated and should not be used.
  publishNotReadyAddresses: false
  ipFamilies:            # This field is deprecated and should not be used.
    - IPv4
  ipFamilyPolicy: SingleStack
  topologyKeys:          # This field is deprecated and should not be used.
    - kubernetes.io/hostname