apiVersion: kodekloud/examplevoting_vote:v1
"kind: Service"
kind: Service
metadata:
  name: vote-service
  namespace: examplevoting
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP