apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: worker-app-container
      image: kodekloud/examplevotingapp_worker:v1
      # The worker app does not expose any ports
      # as it is not a web service, but rather a background worker.