apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: result-app-container
      image: kodekloud/examplevoting_result:v1
      ports:
        - containerPort: 80